spring.application.name=url-shortener-sb

# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/urlshortenerdb
spring.datasource.username=root
spring.datasource.password=Ritik@123


# Hibernate Properties (JPA)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.expiration=172800000
jwt.secret=b012868753ba168b11af0cfc2a84f886ed69b126761a9e3b383784cc80e70d3816c0abf06ba9f6ab7c39523c70b8f44c95a62763dac7ca4563111a2f60898579